# Introduction to Scikit-Learn (sklearn)

This notebook demostrates some of the most useful functions of the beautiful Scikit-Learn library.

What will be cover:

0. An end-to-end Scikit-Learn workflow.
1. Getting the data ready
2. Choose the right estimator/algorithm for our problems
3. Fit the model/algorithm and use it to make predictions on our data
4. Evaluating a model
5. Improve a model
6. Save and load a trained model
7. Putting it all together!

## 0. An end-to-end Scikit-Learn workflow

In [1]:
# 1. get the data ready
import numpy as np
import pandas as pd
heart_disease = pd.read_csv("data/heart-disease.csv")
heart_disease

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [2]:
# Create X (feature matrix)
x = heart_disease.drop("target", axis=1)

# Create y (labels)
y = heart_disease['target']

In [3]:
x

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2

In [4]:
y

0      1
1      1
2      1
3      1
4      1
      ..
298    0
299    0
300    0
301    0
302    0
Name: target, Length: 303, dtype: int64

In [5]:
# 2. Choose the right model and hyperparameters
from sklearn.ensemble import RandomForestClassifier

clf = RandomForestClassifier()

# We'll keep the default hyperparameters
clf.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [6]:
# 3. Fit the model to the training data
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

In [7]:
x_train.size, x_test.size, y_train.size, y_test.size

(3146, 793, 242, 61)

In [10]:
clf.fit(x_train, y_train);

In [11]:
x_train

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
77,59,1,1,140,221,0,1,164,1,0.0,2,0,2
123,54,0,2,108,267,0,0,167,0,0.0,2,0,2
80,41,1,2,112,250,0,1,179,0,0.0,2,0,2
204,62,0,0,160,164,0,0,145,0,6.2,0,3,3
250,51,1,0,140,298,0,1,122,1,4.2,1,3,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3
199,65,1,0,110,248,0,0,158,0,0.6,2,2,1
269,56,1,0,130,283,1,0,103,1,1.6,0,0,3
194,60,1,2,140,185,0,0,155,0,3.0,1,0,2
203,68,1,2,180,274,1,0,150,1,1.6,1,0,3

In [20]:
# make a prediction
y_label = clf.predict(np.array([0, 2, 5, 4, 9, 3]))

/home/nanashi/Desktop/program/machine learning/ml-nutshell/venv/lib/python3.10/site-packages/sklearn/base.py:420: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

ValueError: Expected 2D array, got 1D array instead:
array=[0. 2. 5. 4. 9. 3.].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [21]:
x_test

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
276,58,1,0,146,218,0,1,105,0,2.0,1,1,3
34,51,1,3,125,213,0,0,125,1,1.4,2,1,2
273,58,1,0,100,234,0,1,156,0,0.1,2,1,3
256,58,1,0,128,259,0,0,130,1,3.0,1,2,3
59,57,0,0,128,303,0,0,159,0,0.0,2,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
33,54,1,2,125,273,0,0,152,0,0.5,0,1,2
72,29,1,1,130,204,0,0,202,0,0.0,2,0,2
107,45,0,0,138,236,0,0,152,1,0.2,1,0,2
53,44,0,2,108,141,0,1,175,0,0.6,1,0,2
18,43,1,0,150,247,0,1,171,0,1.5,2,0,2

In [16]:
y_preds = clf.predict(x_test)
y_preds

array([1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1,
       1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1])

In [17]:
y_test

196    0
95     1
62     1
240    0
142    1
      ..
138    1
193    0
276    0
70     1
128    1
Name: target, Length: 61, dtype: int64

In [18]:
# 4. Evaluate the model on the training data and test data
clf.score(x_train, y_train)

1.0

In [19]:
clf.score(x_test, y_test)

0.7540983606557377

In [20]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [21]:
print(classification_report(y_test, y_preds))

              precision    recall  f1-score   support

           0       0.69      0.72      0.71        25
           1       0.80      0.78      0.79        36

    accuracy                           0.75        61
   macro avg       0.75      0.75      0.75        61
weighted avg       0.76      0.75      0.75        61

In [22]:
confusion_matrix(y_test, y_preds)

array([[18,  7],
       [ 8, 28]])

In [23]:
accuracy_score(y_test, y_preds)

0.7540983606557377

In [26]:
# 5. Improve a model
# Try different amount of n_estimators
np.random.seed(42)
for i in range(10, 100, 10):
    print(f'Trying model with {i} estimators..')
    clf = RandomForestClassifier(n_estimators=i).fit(x_train, y_train)
    print(f'Model accuracy on test set: {clf.score(x_test, y_test) * 100:.2f}%')
    print("")

Trying model with 10 estimators..
Model accuracy on test set: 70.49%

Trying model with 20 estimators..
Model accuracy on test set: 80.33%

Trying model with 30 estimators..
Model accuracy on test set: 75.41%

Trying model with 40 estimators..
Model accuracy on test set: 80.33%

Trying model with 50 estimators..
Model accuracy on test set: 77.05%

Trying model with 60 estimators..
Model accuracy on test set: 78.69%

Trying model with 70 estimators..
Model accuracy on test set: 77.05%

Trying model with 80 estimators..
Model accuracy on test set: 80.33%

Trying model with 90 estimators..
Model accuracy on test set: 77.05%

In [27]:
# 6. Save a model and load it
import pickle

# export model
pickle.dump(clf, open("random-forest-model-1.pkl", "wb"))

In [ ]:
# import exported model
loaded_model = pickle.load(open("random-forest-model-1.pkl", "rb"))